# Generated by Django 4.1.6 on 2023-02-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instructor_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_type', models.CharField(max_length=30, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('instructor_login', models.CharField(max_length=100, verbose_name='Логин')),
                ('instructor_password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('instructor_flight_time', models.TimeField(max_length=100, verbose_name='Полетное время')),
                ('aircraft_type', models.CharField(max_length=10, verbose_name='Тип ВС')),
                ('instructor_type', models.CharField(max_length=30, verbose_name='Должность')),
            ],
        ),
    ]
