# Generated by Django 4.1.6 on 2023-03-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_students_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_code', models.CharField(max_length=100, verbose_name='Шифр')),
                ('exercise_name', models.CharField(max_length=10000, verbose_name='Название')),
                ('total_time', models.TimeField(max_length=100, verbose_name='Полетное время')),
                ('instrument_time', models.TimeField(max_length=100, verbose_name='Приборное время')),
                ('night_time', models.TimeField(max_length=100, verbose_name='Ночное время')),
                ('copilot_time', models.TimeField(max_length=100, verbose_name='Время ВП')),
                ('solo_time', models.TimeField(max_length=100, verbose_name='Время самостоятельно')),
                ('PIC_time', models.TimeField(max_length=100, verbose_name='Время КВС')),
                ('PIC_time_enroute', models.TimeField(max_length=100, verbose_name='Время КВС по маршруту')),
                ('PIC_night_time', models.TimeField(max_length=100, verbose_name='Время КВС ночью')),
                ('ground_time', models.TimeField(max_length=100, verbose_name='Время наземной подготвки')),
                ('exercise_type', models.CharField(max_length=100, verbose_name='Тип упражнения')),
                ('approaches', models.PositiveIntegerField(max_length=100, verbose_name='Заходы')),
                ('landings', models.PositiveIntegerField(max_length=100, verbose_name='Посадки')),
                ('equivalent', models.PositiveIntegerField(max_length=100, verbose_name='Заходы')),
            ],
        ),
    ]
